### ISSUE TITLE
能否支持通信流量加密

### ISSUE THREAD

**Issue by hackliu** [shit-hub/gotf#1]
您好，看到你的工具，很实用。
在出差或使用公共网络进行文件产生过程中，工具使用的是明文传输，存在泄露的风险。
工具能否加入通信流量加密功能，加密方式比如AES加密或者使用自签名的SSL证书进行TLS加密。
谢谢，等待您的回复。

**Comment by shit-hub** [comment]
已支持将文件内容进行AES加密，看看是否满足你的需求😄

**Comment by hackliu** [comment]
> 已支持将文件内容进行AES加密，看看是否满足你的需求 😄

非常感谢，这样在公共网络场景中，就不用担心泄露风险了。谢谢
